name: makedoc

on:
  push:
    branches:    
      main

  pull_request:
    branches:    
      main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the doc
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - run: |
        cd docs/ && pip install -r requirements.txt
        make html && cd ..

    - name: Commit doc changes
      run: |
        git clone https://github.com/aicorein/melobot.git --branch gh-pages --single-branch gh-pages
        mkdir tmp-files && cd gh-pages
        mv CNAME .nojekyll README.md .git ../tmp-files
        rm -rf * && rm .buildinfo && cd ..
        cp -r docs/build/html/* gh-pages
        cp docs/build/html/.buildinfo gh-pages
        mv tmp-files/* tmp-files/.git tmp-files/.nojekyll gh-pages
        rmdir tmp-files
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update doc by Github Action" -a || true
        cd ..

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.MELOBOT_PAGE_TOKEN }}
