name: makedoc

on:
  push:
    branches:    
      main

  pull_request:
    branches:    
      main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Build the doc
      run: |
        cd docs/ && pip install -r requirements.txt
        make html && cd ..

    - name: Refresh changes and commit
      run: |
        if git show-ref --quiet refs/heads/gh-pages; then
          echo "gh-pages branch exists"
          git checkout gh-pages
          mkdir .tmp
          mv CNAME .nojekyll README.md .git .tmp/
          mv -r docs .docs
          rm -rf * && rm .buildinfo
          cp -r .docs/build/html/* ./
          cp .docs/build/html/.buildinfo ./
          mv .tmp/* .tmp/.git .tmp/.nojekyll ./
          rmdir .tmp
          rm -rf .docs
        else
          echo "gh-pages branch not exist"
          git checkout -b gh-pages
          touch .nojekyll
          mv -r docs .docs
          cp -r .docs/build/html/* ./
          cp .docs/build/html/.buildinfo ./
          rm -rf .docs
        fi
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update doc by Github Action" -a || true
        cd ..

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: ./
        github_token: ${{ secrets.GITHUB_TOKEN }}
