name: update_deps

on:
  push:
    branches:
      main

  pull_request:
    branches:
      main

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Run tests in Unix-like platform
      if: matrix.os != 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
        for i in $(ls *requirements.txt);
        do
          pip install -r $i
        done
        pytest -c pytest.ini
        if [ $? -ne 0 ]; then
          echo "::error title=Pytest failed::Tests failure"
          exit 1
        fi

    - name: Run tests in Windows platform
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
        Get-ChildItem -Filter *requirements.txt | ForEach-Object { pip install -r $_.FullName }
        pytest -c pytest.ini
        if ($LASTEXITCODE -ne 0) {
            Write-Host "::error title=Pytest failed::Tests failure"
            exit 1
        }
