name: update_deps

on:
  push:
    branches:
      main

  schedule:
    - cron: "0 0 * * *"

jobs:
  update_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup pdm
      uses: pdm-project/setup-pdm@v4

    - name: "Update dependencies"
      run: |
        pdm install
        summary=$(pdm update)
        echo 'SUMMARY<<EOF' >> $GITHUB_OUTPUT
        echo $summary >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
      shell: bash
      id: pdm-update

    - id: detect-changes
      shell: bash
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        echo "---"
        echo $summary
        echo "---"
        echo "${{ steps.pdm-update.outputs.SUMMARY }}"
        echo "---"
